- hosts: webservers
  tasks:
          - name: Configure webserver
            include_role:
                    name: /etc/ansible/roles/myapache 

- hosts: loadbalancer 
  tasks:
          - name: Configure loadbalancer
            include_role:
                    name: /etc/ansible/roles/myloadbalancer 
